### ISSUE TITLE
Do you really need <C-l> and <C-h>?

### ISSUE THREAD

**Issue by adriaanzon** [dkarter/bullets.vim#1]
Nice plugin, I was looking for this.

One small question: do you really need to map `<C-l>` and `<C-h>` to indent? Vim can already do this out of the box with `<C-d>` and `<C-t>`. Or is there any difference?

**Comment by dkarter** [comment]
Thanks @adriaanzon ! Glad you like the plugin!

I actually found out about the built in mappings around the beginning of May and made a mental note to update this plugin but never got around to it.

I wrote about it here:
https://til.hashrocket.com/posts/8de0fb5d93-indent-and-deindent-line-in-insert-mode

This was a good reminder!
