### ISSUE TITLE
feature suggestion: indent after wrap, continue bullets

### ISSUE THREAD

**Issue by bonds** [dkarter/bullets.vim#11]
I ran across the plugin while looking for a solution for this use case: start a list with a asterisk, continue to type even after wrapping. What happens is the text after wrapping starts at column 1, and new lines are not bulletted anymore:

````
* first line blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
blah blah blah blah 
second line blah blah blah blah
third line blah blah blah
````

What I wish would happen is that it would treat the wrapped line as part of the first bullet, indenting it to indicate that, and continue to bullet new lines that were typed (instead of caused by wrapping).

````
* first line blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
  blah blah blah blah 
* second line blah blah blah blah
* third line blah blah blah
````

And it would be nice if it would withstand reflowing and not get screwed up. And I want a pony.

**Comment by dkarter** [comment]
Thank you for submitting this feature suggestion! It is definitely one of the goals of Bullets.vim to support wrapped text in lists, I just have not gotten around to it. 

If you want to have a go at it feel free to submit a PR, otherwise I will try to work on it when I have some free time. Having feature requests for things I want too is definitely motivating. ☺️

**Comment by bonds** [comment]
Cool, thanks for listening. If I take a stab at if before you do, I'll let you know!

**Comment by dkarter** [comment]
Hi everyone, I'm excited to report that this feature is now implemented in v1.3.0!

**Comment by Eetion** [comment]
Thank you!  Does anything special have to be done to activate this feature?  I just tried updating to the most recent version of bullets.vim, but the wrapping looks the same as before.

**Comment by adi-txt** [comment]
Running into the same problem @Eetion faced -- I just installed bullets.vim, the new list item feature works, but my text wrapping is the same as before.

Does having `set wrap linebreak nolist` in my `.vimrc` lead to any issues with this?

**Comment by dkarter** [comment]
@Eetion please see my response in #38 and feel free to chime in there
