### ISSUE TITLE
Auto Indent List after Colon

### ISSUE THREAD

**Issue by BirgerNi** [dkarter/bullets.vim#119]
It would be great to have an option to auto indent a list after a colon. Something like `g:bullets_auto_indent_after_colon`.

The value may set to `0` as default so you don't break any workflows:

```markdown
* line 1
* line 2:
* line 3
```

... and switched to `1` to enable auto indentation:

```markdown
* line 1
* line 2:
  * line 3
```

**Comment by kaymmm** [comment]
Addressed in #130
