### ISSUE TITLE
[enhancement] Add support for pandoc fancy_lists

### ISSUE THREAD

**Issue by bluTaz** [dkarter/bullets.vim#12]
I just came across this plugin today and it's awesome.  When using pandoc, I often use fancy_lists, resulting in the repetitive typing of `#.<space>`. Would you consider adding support for this?

```
#. List 1
#. List 2
   #. Sublist 1
   #. Sublist 2
        #. sub1
        #. sub2
```
[Pandoc Markdown #fancy_lists](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#extension-fancy_lists)

**Comment by dkarter** [comment]
Support added in v1.0.10. Please update and let me know if everything is working for you.

**Comment by bluTaz** [comment]
Awesome; worked wonderfully.
