### ISSUE TITLE
Still that wrap indent problem

### ISSUE THREAD

**Issue by willchao612** [dkarter/bullets.vim#120]
[I have same problem as this issue.](https://github.com/dkarter/bullets.vim/issues/11#issue-231698590)

Turns out this plugin has some conflict with [https://github.com/preservim/vim-markdown](https://github.com/preservim/vim-markdown).

**Comment by dkarter** [comment]
Hello @willchao612, sorry for the late reply on this. Not sure about vim-markdown as I don't use it myself, but maybe there's a way to disable the conflicting functionality in vim-markdown via this flag? https://github.com/preservim/vim-markdown/blob/master/indent/markdown.vim#L11

Alternatively you can disable bullets.vim for markdown files by removing it from the list of enabled file types e.g.

```vim
vim.g.bullets_enabled_file_types = {
  'text',
  'gitcommit',
  'scratch',
}
```

Either way there isn't a plan currently to support vim-markdown's list implementation along side this plugin.
