### ISSUE TITLE
feature suggestion: keep indent from first list item

### ISSUE THREAD

**Issue by hgvhgv** [dkarter/bullets.vim#15]
Thanks for this great plugin!

Like some others here, I also use pandoc. I've started using it via `equalprg` provided by the vim-pandoc plugin to format my own markdown as I write (see <https://github.com/vim-pandoc/vim-pandoc/blob/e9a24376c17817632951088838a3c3bdc1c5da30/doc/pandoc.txt#L177>). 

Pandoc lines up its markdown lists with four spaces after the list marker (see <https://github.com/vim-pandoc/vim-pandoc/blob/e9a24376c17817632951088838a3c3bdc1c5da30/doc/pandoc.txt#L177>). It looks like:

```
*    Item 1
    *    Subitem 1a
    *    Subitem 1b
*    Item 2
*    Item 3
    *    Subitem 3a
         *    Subitem 3ai
```

It would be great if the indentation (no matter how long—four spaces or otherwise) of the first list item were preserved when this plugin adds the next list item with "\<CR\>" or "o"—just to keep it all consistent as I'm writing before I reformat the entire doc. This is possibly related to the other open feature request on indentation (#11). File under "would be nice" but of course not pressing.

**Comment by pitkling** [comment]
I second this request, would be really a welcome feature :).
