### ISSUE TITLE
feature suggestion: add/remove a checkbox to a line

### ISSUE THREAD

**Issue by bhrutledge** [dkarter/bullets.vim#17]
For example, a normal-mode mapping to toggle between `- List item` and `- [ ] List item`.

Or, more broadly, a way to select or cycle through bullet types on a line.

**Comment by dkarter** [comment]
That's a neat suggestion, and doesn't sound too hard to do - would you like to give it a shot with a PR?

**Comment by bhrutledge** [comment]
I'm going to pass; I'm currently experimenting with other editors. Might come back to Vim, but either way, not in a place to do plugin development. :)
