### ISSUE TITLE
Feature suggestion: Custom bullets

### ISSUE THREAD

**Issue by hrai** [dkarter/bullets.vim#19]
I use vim extensively to create JIRA description documents. While doing so, I often have to have custom indents like (**, *** etc.)

It would be great if we could add this as a configurable feature.

**Comment by dkarter** [comment]
Hi @hrai, I just merged the PR from @hut #18 . It's not the solution you are suggesting, but should hopefully fulfill what you are trying to do. Let me know if not and I can re-open the issue.

I am totally open to the idea of custom simple bullets or even allowing callbacks that accept the previous bullet and return what the next one should be for more complex bullet types. If you feel comfortable submitting a PR I'd be happy to work with you on that.
