### ISSUE TITLE
E706: Variable type mismatch for: l:bullet

### ISSUE THREAD

**Issue by securitygeneration** [dkarter/bullets.vim#2]
Installed the latest version of bullets.vim using Plug in Vim 7.4 on both Linux and macOS. Trying to create any kind of bullet list in a text or markdown file yields the following error:

```
Error detected while processing function <SNR>18_insert_new_bullet:
line 18:
E706: Variable type mismatch for: l:bullet
```

![error](https://cloud.githubusercontent.com/assets/1046239/23059502/9ab14e96-f4f1-11e6-967e-ce8435adf567.png)

I also tried using a minimal vimrc to rule out any issues there, but the result is the same.

**Comment by dkarter** [comment]
Thanks for the bug report. I was able to reproduce on a fresh copy of Kali Linux with Vim 7.4 and Plug. Working on fix and will update you when I have one.
