### ISSUE TITLE
Add configuration option to prevent deletion of last bullet

### ISSUE THREAD

**Issue by dkarter** [dkarter/bullets.vim#3]
see https://twitter.com/securitygen/status/832725395078123520

**Comment by viniciusarcanjo** [comment]
@dkarter thank you for this awesome plugin! much appreciated.

**Comment by securitygeneration** [comment]
Thank you indeed!

**Comment by dkarter** [comment]
Fixed in 1.0.5. 

Glad you find it useful and thank you for the improvement requests!
