### ISSUE TITLE
Does not work in insert mode with paste enabled

### ISSUE THREAD

**Issue by daniel-vera-g** [dkarter/bullets.vim#30]
This issue follows to the more general #29 where I could not use this plugin in insert mode.

The reason for this is that the setting `set paste` in my `.vimrc` prevented it. After removing `set paste` from it, it works.

Also when activating `set paste` to paste something, the plugin does not work.

I am not so fluent in ruby and vimscript, to propose a fix. But maybe a workaround to use `paste` and the plugin together is possible.

**Comment by dkarter** [comment]
This is intentional and is a feature of Vim to eliminate errors in pasting. See my comment on #29.
