### ISSUE TITLE
[bug] Inserting a new line above a bullet doesn't insert a bullet

### ISSUE THREAD

**Issue by alichtman** [dkarter/bullets.vim#34]
Pressing `o` on a bullet line creates a new bullet on the new line.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/20600565/62660824-d4bb6680-b934-11e9-80d0-e9e098d0248f.png">

Pressing `O` on a bullet line creates an indented line on the line above without adding a bullet at the beginning.

<img width="166" alt="image" src="https://user-images.githubusercontent.com/20600565/62660873-f288cb80-b934-11e9-978f-55d87c073969.png">

**Comment by dkarter** [comment]
Hi @alichtman! 

This is not a bug. Think of this more as feature parity with normal word processors. It doesn't seem like a natural way for me to create bullets by going up.

If a bullet was created with `O` and was unwanted, the user would have to hit backspace twice. This is not convenient workflow in my eyes. When a bullet is created with `o` and is unwanted pressing `<CR>` again without typing anything will delete it (just like TextEdit, MS Word etc).

I see your point though. If this feature was to be added, it should only work in a middle of a bullet list (as in your screenshot) and not when `O` is pressed at the top of a bullet list. Feel free to submit a PR :)

**Comment by alichtman** [comment]
Yep, I see where you’re coming from now. Not sure that this is actually a feature I’d want, now that I think about it...
