### ISSUE TITLE
<CR> and TAB are inserted after deleting an empty bullet

### ISSUE THREAD

**Issue by AdamWysokinski** [dkarter/bullets.vim#41]
Vim 8.2.50,  latest version of bullets installed.
When I close the bullet list with Enter, Vim deletes the empty bullet point (as expected) and then inserts <CR> and TAB (as not expected), like this:
```
* line 1
* line 2

    <
```
This happens when plasticboy/vim-markdown is enabled and only for * bullets.
Any ideas how to modify this behavior?

**Comment by dkarter** [comment]
Looks like vim-markdown has it's own support for bullet lists so if you want to use it with bullets.vim you may want to disable it's bullet feature: https://github.com/plasticboy/vim-markdown/blob/da5a7ac96f517e0fd6f886bc3fbe27156ca1f946/doc/vim-markdown.txt#L469
