### ISSUE TITLE
Bullets is messing with the abbreviations

### ISSUE THREAD

**Issue by samarulmeu** [dkarter/bullets.vim#42]
I have some abbreviations defined with new lines inside them and they work as expected when _bullets_ is disabled, but totally different with the plugin. 

Something like this:

```
ab artcl
\<CR>---
\<CR>title: ""
\<CR>description: ""
\<CR>---
```

Normal output should be:

```
---
title: ""
description: ""
---
```

But *bullets* transforms it into:

```
---title: ""description: ""---



``` 

(notice the inserted lines at the end).

Bullets is an amazing plugin for markdown and I would like to use it further, if this could be resolved.

**Comment by kaymmm** [comment]
I can't reproduce this. A quick rspec test that I wrote to test this case also passes without issue. Have you tried disabling all of your other plugins and using an empty .vimrc to determine if perhaps this plugin is conflicting with something else in your configuration? It may be the case that the way that this plugin currently configures its mappings is interfering with something on your end.

**Comment by samarulmeu** [comment]
Thank you for your answer. When I first stumble upon this, after disabling _bullets_ plugin, abbreviation started working again, so I did not investigate further. In the mean time, I solve it with a workaround using snippets which are more versatile than abbreviations.
