### ISSUE TITLE
Bullets does not work for empty filetype

### ISSUE THREAD

**Issue by linjiX** [dkarter/bullets.vim#44]
For some no extension text file. Vim will treat its filetype as 'empty'.
```
:set filetype?
> filetype=
```
I tried to add `''` into `let g:bullets_enabled_file_types`
```
let g:bullets_enabled_file_types = {''}
```
But it doesn't work,
Can bullets be enabled for these empty filetype files?

**Comment by dkarter** [comment]
There is a flag for that: 

```
let g:bullets_enable_in_empty_buffers = 1
```

Should be enabled by default! (you may need to remove the `g:enabled_file_types` - seems like you were trying to set it to an object which is incorrect - it needs to be an array of strings, like so:

```
let g:bullets_enabled_file_types = ['markdown', 'text', 'gitcommit']
```

But for now I recommend you remove it until you actually need to set it and check if bullets work for you in empty buffers as it does for me.
