### ISSUE TITLE
[Feature Request] Add a flag to disable text object mappings

### ISSUE THREAD

**Issue by linjiX** [dkarter/bullets.vim#45]
The default bullet text object mapping `ab` `ib` is conflict with vim default text object for parenthesis.
We only have a flag to disable all mappings `g:bullets_set_mappings`
Could you provide an extra flag to just disable text object mappings.

**Comment by dkarter** [comment]
I'm going to remove those altogether in an upcoming update. I don't find them all that useful anyway and have not kept them up to date with all the updates that have been going on over the years to support multiple bullet types.
