### ISSUE TITLE
Add support for latex enumerate/itemize environemnts

### ISSUE THREAD

**Issue by kiryph** [dkarter/bullets.vim#5]
Would you consider extending your plugin to support latex?

There would be following use case for latex documents:

```tex
\documentclass{article}

\begin{document}

\begin{itemize}
  \item First item
  \item Second item
  \item \ldots
\end{itemize}

\end{document}
```

**Comment by dkarter** [comment]
Implemented in 1.0.7

**Comment by kiryph** [comment]
Thanks for the quick addition.

I would have two further wishes:

1. Would it be possible to add the (optional) behaviour when pressing `<CR>` two times the auto inserted item is removed but no additional line is inserted yet. So the second `<CR>` would just mean delete list specifier but no new line. Only when I press `<CR>` the third time another new line would be inserted.
2. This would be more complicated. I do not use softwrapping but hardwrapping of my code.  
    ```tex
   \begin{itemize}
    \item First long item  \ldots
       This is still the first item. Can auto-insertion of item also be triggered here?
   \end{itemize}
    ```
    In latex this situation could be identified as long as the immediate surrounding environment is one of `itemize/enumerate/description` we are still within  the list. However, since your plugin is more generic, this could not be used for markdown etc.  
As a comprise I could think of following: as long as there is no empty/whitespace-only line between the current line and the last line with a leading item specifier, the plugin can assume the user is still adding text to the same item in the current list.

I hope I made myself what I mean. Anyhow, thanks for the plugin.

**Comment by kiryph** [comment]
I think I will use for latex the mappings
```viml
function! AddItem()
  let [end_lnum, end_col] = searchpairpos('\\begin{', '', '\\end{', 'nW')
  if match(getline(end_lnum), '\(itemize\|enumerate\|description\)') != -1
    return "\\item "
  else
    return ""
  endif
endfunction
inoremap <expr><buffer> <CR> getline('.') =~ '\item $' 
  \ ? '<c-w><c-w>' 
  \ : (col(".") < col("$") ? '<CR>' : '<CR>'.AddItem() )
nnoremap <expr><buffer> o "o".AddItem()
nnoremap <expr><buffer> O "O".AddItem()
```
which I have put into `~/.vim/after/ftplugin/tex.vim`.
