### ISSUE TITLE
Feature request to toggle check box

### ISSUE THREAD

**Issue by ErickChacon** [dkarter/bullets.vim#61]
A more advanced toggle check would be useful for this plugin. I think the three scenarios below are essential. However, I will understand it goes beyond the scope of the plugin.

- First: Toggle all the children below the current checkbox. For example, if I mark checkbox `b`,
```
- [ ] a
- [x] b
  - [ ] b1
  - [ ] b2
- [ ] c
```
I expect that their children are also marked.
```
- [ ] a
- [x] b
  - [x] b1
  - [x] b2
- [ ] c
```
Similarly, in the case that I unmark a checkbox, I will expect that their children are also unmarked.

- Second: Half-check the parent, if a subset of all the children is marked. For example, If I mark `b1`, 
```
- [ ] a
- [ ] b
  - [x] b1
  - [ ] b2
- [ ] c
```
I expect that the parent is  `b` is half-marked.
```
- [ ] a
- [o] b
  - [x] b1
  - [ ] b2
- [ ] c
```

- Third: Parent should be updated as marked if all the children are marked. Continuing with the previous example, If I mark `b2`,

```
- [ ] a
- [o] b
  - [x] b1
  - [x] b2
- [ ] c
```
then `b` should be updated as `marked'.
```
- [ ] a
- [x] b
  - [x] b1
  - [x] b2
- [ ] c
```

**Comment by yaohunzhanyue** [comment]
Just to let you know, vimwiki could do this trick. It also supports making a checkbox for the record.
```
autocmd filetype vimwiki nnoremap <buffer> <silent> ,x :VimwikiToggleListItem<CR>
autocmd filetype vimwiki inoremap <buffer> <silent> ,x <Esc>:VimwikiToggleListItem<CR>a
```

**Comment by ErickChacon** [comment]
Hi @yaohunzhanyue, thanks for the suggestion. I am a `vimwiki` user and I know that you can do it with `vimwiki`. However, I want to stop using `vimwiki` given that it has many features that are not of my interest. That is the reason I now prefer to use `bullets.vim` inside markdown. I really like `bullets.vim` because you can use it in any filetype `rmd`, `pandoc`, etc. To use this feature with `Vimwiki`, I will have to change the filetype of `rmd`, `pandoc`, etc to `vimwiki`; which is undesirable for my case.

**Comment by kaymmm** [comment]
I submitted a PR #65 that adds this feature. Feel free to take a look at the PR and test it out to see if it does what you expect it to do.

**Comment by ErickChacon** [comment]
Wow! This is amazing @kaymmm. It works as expected, thank you.

**Comment by dkarter** [comment]
@all-contributors please add @ErickChacon for ideas
