### ISSUE TITLE
Nested bullet outlines bug

### ISSUE THREAD

**Issue by yaohunzhanyue** [dkarter/bullets.vim#62]
1. Can't auto change to up level type when unindent.
2. Can't be renumbered by RenumberSelection.

**Comment by kaymmm** [comment]
I believe these issues are both addressed by #56. Waiting on merge by @dkarter.

**Comment by dkarter** [comment]
@yaohunzhanyue I've merged #56, can you confirm this is now resolved?

**Comment by BSDxxxx** [comment]
@dkarter Yes, this has been fixed, thanks.

**Comment by yaohunzhanyue** [comment]
This has been fixed.  
Thanks.
