### ISSUE TITLE
Updating a list is quite slow (profile attached)

### ISSUE THREAD

**Issue by harshad1** [dkarter/bullets.vim#68]
I have found that updating a list (for example, by indenting a line in the middle) is quite slow. 

To test this I did the following:
1. Created a file with 100 identical lines, numbered from 1 to 100 (attached number.txt)
2. Started profiler
3. Indented 10 lines (#40 -> #50) by 1 indent
4. Paused profiler

The renumbering appears to have taken 3.8 seconds on my relatively fast laptop (i7-8850h). Several functions appeared to have been called > 2K times.

[number.log](https://github.com/dkarter/bullets.vim/files/4569565/number.log)
[number.txt](https://github.com/dkarter/bullets.vim/files/4569566/number.txt)

**Comment by dkarter** [comment]
Fixed in #69
