### ISSUE TITLE
delete_last_bullet  suggestion

### ISSUE THREAD

**Issue by giceli** [dkarter/bullets.vim#75]
what I want to enter at "this is a markdown test 2" is :
> \*  this is a test 1
> &nbsp;&nbsp;&nbsp;&nbsp;\```markdown
>  &nbsp;&nbsp;&nbsp;&nbsp;this is a markdown test 1
> &nbsp;&nbsp;&nbsp;&nbsp;this is a markdown test  2
> &nbsp;&nbsp;&nbsp;&nbsp;\```
> \* this is a test 2

but the actually is :
> \*  this is a test
> &nbsp;&nbsp;&nbsp;&nbsp;\```markdown
> &nbsp;&nbsp;&nbsp;&nbsp;ths is a markdown test 1
> * 
>  &nbsp;&nbsp;&nbsp;&nbsp;\```
> \* this is a test 2

so how can I change it.

**Comment by dkarter** [comment]
This is supported by bullets.vim. You would need to have your terminal emulator send the correct escape code for `<C-CR>` (Ctrl + Enter). There is a short guide on that here: https://stackoverflow.com/a/42461580/77131

Here's an example of the use in iTerm on mac:

![2020-05-10 18 20 16](https://user-images.githubusercontent.com/551858/81513088-681e2f80-92eb-11ea-8180-063b185c6e18.gif)
