### ISSUE TITLE
bullets_outline_levels 'ABC'  'abc' malfunction starting at C

### ISSUE THREAD

**Issue by aodecipher** [dkarter/bullets.vim#80]
It's using the default outline levels. Seems like C and D consistently loops back to A, if <C-T> the following item. Once it gets to E, it's normal again.
This problem persists, although in different ways, even if I change the outline-levels to a different order.
Update: 'abc' turns out to have the same issue. It's only when demoting, promoting works fine.

<img width="470" alt="Screen Shot 2020-06-04 at 3 58 41 PM" src="https://user-images.githubusercontent.com/36972598/83804870-d3ee8080-a67c-11ea-98ae-fdc22cab4903.png">

**Comment by harshad1** [comment]
@aodecipher Could you check if this issue still exists? My related issue, #67, appears to have been resolved

**Comment by aodecipher** [comment]
> @aodecipher Could you check if this issue still exists? My related issue, #67, appears to have been resolved

I have heavily modified the source code, and bypassed the problem by changing how new bullets are generated, so I can't check it with my current settings. Thanks for your reply though.
