### ISSUE TITLE
Using hyphen/dash and indenting with ctrl-t makes subsequent bullets asterisks

### ISSUE THREAD

**Issue by areographe** [dkarter/bullets.vim#87]
Hi, just adapting to the change from LibreOffice to vim for note-taking while I'm studying, and I noticed that if I start a list with hyphen characters, and then use ctrl-t to indent an item at the next sub-level, it changes to an asterisk, and any subsequent indents continue to use asterisks. The expected result of:

```
- list item 1
	- sub-item 1
```

doesn't happen, and instead I get

```
- list item 1
	* sub-item 1
```

Is there a config option I'm missing to retain the hyphen at every level when indenting?

**Comment by dkarter** [comment]
You can set `let g:bullets_outline_levels=[]` in your vimrc to disable this.

If you want to add more clarity to the docs I'm happy to accept a PR :)
